version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_testProj07Project
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser
  gitUsername: siqagituser
  gitBranch: main
- name: PackageA
  gitServerName: SIQAPsur
  gitUrl: https://github.com/prabhakarsag
  gitUsername: prabhakarsag
  gitBranch: main
- name: PackX
  gitServerName: SIQAPsur
  gitUrl: https://github.com/prabhakarsag
  gitUsername: prabhakarsag
  gitBranch: main
